#!/bin/sh

set -ue

PATH="/usr/local/bin:$PATH"

echo "Checking for .github/workflows/build.yml.jinja changes..."

if [ "$(git diff-index --cached HEAD --name-only)" != "" ]
then

	files=( $(git diff-index --cached HEAD --name-only) )

	for file in ${files[@]}
	do
		if [ "$file" == ".github/workflows/build.yml.jinja" ] || [ "$file" == "render_build_yml.py" ]
		then
			echo "Change detected, re-rendering GitHub Actions"
			pipenv run python render_build_yml.py
			git add .github/workflows/*.yml || true
		fi

		case $file in
			*.py)
				if [ -f "$file" ]
				then
					pipenv run black $file
					git add $file
				fi
				;;
		esac
	done
fi
