#!/bin/sh

set -ue

PATH="/usr/local/bin:$PATH"

if [ "$(git diff-index --cached HEAD --name-only)" != "" ]
then

  files=( $(git diff-index --cached HEAD --name-only) )

  render_readme=no
  render_github_workflow=no
  for file in ${files[@]}
  do
    case $file in
      *.yml.jinja) render_github_workflow=yes;;
      *.md.jinja) render_readme=yes;;
      *.py)
        render_readme=yes
        render_github_workflow=yes
        pipenv run black $file
        git add $file
    esac
  done

  case $render_github_workflow in
    yes)
      pipenv run ./render.py github-workflows
      git add .github/workflows/*.yml
      ;;
  esac
  case $render_readme in
    yes)
      pipenv run ./render.py readme
      git add README.md
      ;;
  esac
fi
