name: Delete stale draft releases
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 */2 * * *'

jobs:
  render:
    name: Delete stale draft releases
    runs-on: ubuntu-latest

    steps:
    - name: Delete stale draft releases
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -uexo pipefail
        sudo add-apt-repository ppa:cpick/hub
        sudo apt-get update -q -y
        sudo apt-get -qq install -y install hub

        delete_release () {
          echo "Deleting release: $1 ($2)"
          hub release delete $2
        }

        keep_release () {
          echo "Keeping release: $1 ($2)"
        }

        now=$(date +%s)
        three_days=259200
        eval "$(hub release -L 200 --include-drafts -f "([ \"\$(expr $now - %ct)\" -ge '$three_days' ] && [ '%S' = 'draft' ] && delete_release '%t' '%T' || keep_release '%t' '%T') ; ")"
