name: Check for new versions of Nim
on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  render:
    name: Render github workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check for new Nim versions
        shell: bash
        run: |
          set -uexo pipefail

          pip install -r requirements.txt
          python3.9 render.py github-workflows
          python3.9 render.py readme

          git config --global user.email "elijahr+gha@gmail.com"
          git config --global user.name "GitHub Actions"

          git add .github/workflows/*.yml || true
          if [ "$(git diff --name-only --cached | grep .github/workflows)" != "" ]
          then
            git commit -m "Re-rendered github workflows"
          fi

          git add README.md || true
          if [ "$(git diff --name-only --cached | grep README.md)" != "" ]
          then
            git commit -m "Re-rendered README.md"
          fi
          git push || (git pull origin && git push || true)
