name: Check for new versions of Nim
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  render:
    name: Render build.yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check for new Nim versions
        shell: bash
        run: |
          set -uexo pipefail

          pip install -r requirements.txt
          python3.9 render_build_yml.py
          git add .github/workflows/build.yml || true
          if [ "$(git diff --name-only --cached | grep .github/workflows/build.yml)" != "" ]
          then
            yamllint .github/workflows/build.yml
            git commit -m "Re-rendered build.yml"
            git push
          fi
